name: Despliegue Automatico a Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cargar codigo fuente
      uses: actions/checkout@v4

    - name: Configurar Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Enviar a Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'nexova-business-group'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
